#!/usr/bin/env python
# Written by: DGC
import time
t_start = time.time()
print("RUNNING PROBLEM 29")
print("How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?\n")

powers = []
distinct_powers = []
for i in range(2,100+1):
    for j in range(1,100+1):
        powers.append(pow(i,j))
powers.sort()
for k in range(0,len(powers)-1):
    if (powers[k] != powers[k+1]):
        distinct_powers.append(powers[k])
print(len(distinct_powers))
#print("run time:"),
#print(str(time.time()-t_start))
