#!/usr/bin/env python
# Written by: DGC
import time
import primes

t_start = time.time()
print("RUNNING PROBLEM 046")

limit = 1000000
primes = primes.primes_bellow(limit)
print("calculated primes")
squares = []
i = 1
while (True):
    sq = i*i
    if (sq > limit):
        break
    squares.append(sq)
    i += 1
print("calculated squares")

for potential in range(33,limit,2):
    good = True
    if potential in primes:
        continue
    for p in primes:
        if (p > potential):
            break
        for s in squares:
            if (potential == p + s*2):
                good = False
                continue
    if (good):
        print(potential)
        break

print("run time:"),
print(str(time.time()-t_start))
    



